### ISSUE TITLE
Oinkzone should stay static in road editor

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#100]
# Defectus Demonstrandum

## Reseminata

1. Go to the road editor for any goal
2. Zoom in on the nozone aka pinkzone aka oinkzone
3. Drag the part of the road adjacent to the nozone up and down

## Expectata

The nozone should stay put.

## Resultata

The grayed-out effect (diagonal faint gray lines) does stay put but the pink shading follows the dragging of the road. Like in the following screenshot the pink shading should extend all the way up to the dotted line, where the road was before I started dragging it:

![image](https://user-images.githubusercontent.com/9928/77112443-4341c600-69e6-11ea-8fda-ef69d5da858c.png)

*Defectus delenda est!*

**Comment by saranli** [comment]
The reason for this is that the pink coloring is generated by updateYBHP, which respects the new road. updatePinkRegion does the pattern shading. The solution I found is to disable the pink coloring in the YBHP update function, and add background fill to the pattern definition at the beginning (pinkzonepat)

**Comment by dreeves** [comment]
This fixes a more general problem too, with the pink and gray-diagonal regions mismatched:

![image](https://user-images.githubusercontent.com/9928/88834333-8aa44400-d188-11ea-852e-53bc27b9fec3.png)

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3476
http://beeminder.com/changelog#3477
