### ISSUE TITLE
Missing yellow guiding lines on flat road

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#104]
From shanaqui:

Pre-ybhp:

![image](https://user-images.githubusercontent.com/9928/79076020-8f152180-7cab-11ea-8d7d-3190b1432015.png)

YBHP:

![image](https://user-images.githubusercontent.com/9928/79076026-9b00e380-7cab-11ea-944e-77c868d9cc4c.png)

BB file in privatesuite as ybhp-missing-glines.bb

**Comment by bsoule** [comment]
added 3 new ones to private suite.

```
data/missing-ybhp-lines1.bb
data/missing-ybhp-lines2.bb
data/missing-ybhp-lines3.bb
```

**Comment by dreeves** [comment]
And data/glines-stop-early.bb from Adam:

Pre-YBHP:

![image](https://user-images.githubusercontent.com/9928/82079014-fd784580-9696-11ea-9713-28cbdc0408ff.png)

YBHP:

![image](https://user-images.githubusercontent.com/9928/82079084-141e9c80-9697-11ea-8c7a-f00c4359583a.png)

**Comment by dreeves** [comment]
https://github.com/beeminder/road/issues/104
