### ISSUE TITLE
Grayson dots (actually forest green) for 7+ safe days (aka akrasia horizon immunity)

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#111]
Related to #106

AKA "gray(son) dots"

At least make the color for 7+ days of buffer be subtly different. Gray or a more gray-ish green.

https://forum.beeminder.com/t/beeminder-anti-habit-forming/6300/19?u=dreev

![image](https://user-images.githubusercontent.com/9928/94462579-9a340f00-0170-11eb-94bb-3b0112cb2ecf.png)

**Comment by dreeves** [comment]
Here's a candidate Before / After. I figured I'd start with a very subtle change but Bee is pointing out that it doesn't look intentional this way, just like the green is bit messed up.

![image](https://user-images.githubusercontent.com/9928/92958129-896c6500-f41e-11ea-87d9-f980ebc3b270.png)

**Comment by shanaqui** [comment]
Grey reads really odd to me, here. It sort of feels like it's saying it's invalid somehow (because "greyed out" often means "this option is disabled". 

I am not sure what better colour I could suggest, but that was my first reaction. Even knowing Beeminder graphs as well as I do, it was very much "these are... dead? datapoints?"

**Comment by chipmanaged** [comment]
I was just scrolling down to say exactly what @shanaqui said. Grey usually means "invalid", "temporary", "unalterable", "system-set", or some other thing of that type. (It'd be great for PPRs, though! A visual indicator that you need to ENTER YO DATA!)

**Comment by dreeves** [comment]
[prescript: I typed this after shanaqui's comment but then sat on it because I wanted to update the forum thread and everything too. clearly i'm not going to do that but let's try to limit gissue discussion to the technical questions.]

Ok, that was persuasive, @shanaqui. (I'm still torn because of how great "Gray(son) dots" was but I _guess_ that's secondary to the aesthetics and the actual semantics.)

So what if we make the akrasia-immune dots forest green? (See new before/after image in top-level comment above.) Like you're so far above the yellow brick road that you're off in the forest? It's a subtle difference so maybe that's fine to start with.

The hard thing about actually deploying this is we need to coordinate Beebrain + Beebody + Beedroid + BeemiOS so they all use colors consistently. Here's what everything should implement:

```
color = (safebuf < 1 ? "#ff0000" :  # Red for beemergencies
         safebuf < 2 ? "#ffa500" :  # Orange for 1 safe day
         safebuf < 3 ? "#3f3fff" :  # Blue for 2 safe days
         safebuf < 7 ? "#00aa00" :  # Green for 3+ safe days
                       "#228B22")   # Forest green Grayson dots for 7+ safe days
```

**Comment by dreeves** [comment]
UPDATE: We're going to have the API just return `color` as a goal attribute so clients don't have to implement the mapping from safebuf to color.

Danny and Bee can talk about how/whether this can be DRY'd up between Beebrain and Beebody.

**Comment by dreeves** [comment]
Another before/after where you can see how the dots are dark green when they pass the green isoline:

![image](https://user-images.githubusercontent.com/9928/96323738-63b11d80-0fd3-11eb-9396-95fc2b8e1daf.png)

**Comment by chipmanaged** [comment]
I like it!
