### ISSUE TITLE
BUG: YBHP needs to force lnw=0

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#113]
(This started as a nebulous bug with d/beemail where it was showing orange when it should be red and saying +0 due when it should say +1 due.)

Bee and I are in the middle of figuring this out. We first need to deploy the latest Beebrain to production to rule out differences there. [DONE; that wasn't it]

Q: Will bmndr.co/d/beebrain still say 0 due on a beemergency day on Apr 29?

But also we have spuriously-orange.bb outputting lnw>0 despite ybhp=true so probably it should not do that and also we want to see where, if anywhere, Beebody cares about that.

**Comment by bsoule** [comment]
deployed master to production today around 2:30pm. The bug is still there with d/beemail.

To make it more precise: when ybhp=true && abslnw=0 it reports limsum and (bbody computes baremin/hardcap) correctly. When ybhp=true && abslnw=nil both beebrain and bbody get the baremin/hardcap numbers wrong and say "0 due in 2 days"

**Comment by dreeves** [comment]
In spuriously-orange.bb, if abslnw==null:

* "safebump":982.7142857142852
* "lnw":0.6428571428571429
* "delta":-0.3571428571423212
* "vcur":983
* "limsum":"0 in 0 days"

If abslnw==0:

* "safebump":983.3571428571423
* "lnw":0
* "delta":-0.3571428571423212
* "vcur":983
* "limsum":"+1 in 0 days"

**Comment by bsoule** [comment]
note that `safebump_null + lnw_null === safebump_zero`

(like, obviously you shouldn't be computing a lnw of 0.64 for a ybhp goal, but that appears to be the thing that's messing up safebump, as safebump is exactly one lnw too small.

**Comment by dreeves** [comment]
The following is fixed by the bugfix for this gissue:
https://forum.beeminder.com/t/0-due-in-16-days-and-other-x-due-in-y-oddities/6636?u=dreev
