### ISSUE TITLE
Wrongly red dot for completed goal

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#126]
## Reseminata

See mary-news-wrong-red.bb in private suite.

## Expectata

Final dot, slightly above the bull's eye, is green.

## Resultata

Dot is red! That contradicts the due-by table which says +0 is due.

## Nota Nebulosa

MARY: It's not altered by my changing the "precision" to 1.0e-05, for whatever that's worth.

(Not certain this is a regression but seems like we'd've noticed it before if not. Maybe.)

**Comment by chipmanaged** [comment]
After the deadline (Added a +0 datapoint to make it refresh):

![Screen Shot 2020-06-09 at 4 02 34 PM](https://user-images.githubusercontent.com/10947385/84194211-b0f01200-aa6a-11ea-9811-65670bff068a.png)

**Comment by chipmanaged** [comment]
(I.e. time's up... but it didn't end)

**Comment by dreeves** [comment]
See also mary-wrong-color-smiley.bb for (presumably) another case of this.

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3459
