### ISSUE TITLE
Purple line doesn't start at agg'd day on day 1

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#129]
Philip: Rendering bug in ybhp on wean? Expected the day one line to start at zero, not render down from that day’s max. i.e. like day two has done, showing the datapoints but not running a line through them.

![image](https://user-images.githubusercontent.com/9928/85425456-0da10180-b52e-11ea-8549-cb593ac5af2a.png)

This is pjh-wonky-wean-start.bb in the test suite.

**Comment by saranli** [comment]
I checked the code and it seems like this was a feature specifically implemented in the code. I am guessing I copied that from pybrain. Let me know if you want to eliminate that so the first aggregated point is where the steppy line should start from. It involves removing code that introduces the special case for the initial point.

**Comment by dreeves** [comment]
Huh, you're right. It's coming back to me now: for a do-more goal it's nice to see all the vertical segments, that being the point of the steppy line, including the initial vertical segment. So we have that special case to make the steppy line start at {tini,vini} even though there's no agg'd datapoint there.

It seems we tried to make that too general because Phillip is right that it's weird to do this in the above case. I suspect the problem is only conditioning on `dir<0`. As usual, we probably need to consider each of the 4 Platonic goal types separately. 

Here's the Python:

```python
# Plot the purple steppy line, plus a bigger purple dot at each datapoint
def grSteppy():
  a = tini # maybe more efficient to max w/ the datapoint just left of tmin
  b = min(asof, tmax) # stop the steppy line at asof or tmax, whichever's first
  
  # First plot the purple steppy line without the dots, including flatlined pt
  if tini in allvals: dpre = [(tini, max(allvals[tini]) if dir<0 else \
                                     min(allvals[tini]))]
  else:               dpre = []
  d = dpre + [(t,v) for t,v in aggval.items() if a<=t<=b] 
  if flad is not None: d += [flad] # append the flatlined datapoint
  d.sort()
  pd(d, color=PURP, fmt='bo', marker='None', linestyle='steps-post-',
        drawstyle='steps-post', linewidth=.9*scalf)
  # Now draw the actual purple dots, except the flatlined point
  a = max(tini, tmin)
  d = [(t,v) for t,v in aggval.items() if a<=t<=b]
  d.sort() # uluc bug fix
  pd(d, color=PURP, fmt='bo', marker='o',linestyle='None', markeredgewidth=0,
        drawstyle='steps-post', markersize=2.8*scalf, linewidth=.9*scalf)
```

And here's the Javascript (just the part with that special case):

```javascript
if (   dataf[0][0] > l[0] 
    && dataf[0][0] < l[1] && dataf[0][0] in bbr.allvals) {
  // Handle the initial point
  var vals = bbr.allvals[dataf[0][0]].map(e=>e[0])
  var vpre = (goal.dir<0)?bu.arrMax(vals):bu.arrMin(vals)
  d = "M"+r1(nXSc(dataf[0][0]*SMS))+" "+r1(nYSc(vpre))
  d += "L"+r1(nXSc(npts[0][4]*SMS))+" "+r1(nYSc(npts[0][5]))
} else {
  d = "M"+r1(nXSc(npts[0][4]*SMS))+" "+r1(nYSc(npts[0][5]))
}
```

**Comment by dreeves** [comment]
I looked at this again and I think it's just that we want to take the first entered datapoint as the point to draw the purple vertical segment from.

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3565
