### ISSUE TITLE
Spurious half-plane shading

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#130]
## Reseminata

1. Generate the graph defined by kk-why-shade.bb in the private suite.

## Expectata

Normal thin yellow isolines graphed.

## Resultata

The entire good side of road is shaded yellow.

![image](https://user-images.githubusercontent.com/9928/88830149-65143c00-d182-11ea-9572-7ac692cdabd0.png)

**Comment by dreeves** [comment]
Update: krugerk has had this happen to another of their goals in the meantime. Priority++!

**Comment by saranli** [comment]
I could not reproduce this. Screenshot maybe?

**Comment by dreeves** [comment]
Screenshot added. And I may have figured this out! Or at least have a huge hint. If you remove the "tmin" you can see this starts with a very step segment and the isolines look normal. I'm still confused about that but it may be fine or just too cornercasey to care.

**Comment by saranli** [comment]
Based on my brief thinking, the code that decides on whether to shade or not does not exactly clip the last isoline to the graph range, just selects intersecting isolines, I think. It might be better to implement a version which clips the isoline to graph boundaries from the left and right and checks whether that is entirely contained in the visible part or not.

**Comment by dreeves** [comment]
After shot:

![image](https://user-images.githubusercontent.com/9928/90835417-6956f380-e301-11ea-9cc3-7b1f8837497a.png)
