### ISSUE TITLE
Don't add event listeners for headless graph generation

### ISSUE THREAD

**Issue by saranli** [beeminder/road#144]
I just noticed that, particularly for datapoints, adding event listeners is not conditioned on whether the graph is headless or not and takes a lot of time. Conditioning that on interactive graphs could substantially accelerate goals with lots of datapoints. Same goes for other graph elements, probably.

**Comment by saranli** [comment]
Just tested this roughly on the privatesuite, seems like it results in about %3 improvement on average processing time.

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3129
