### ISSUE TITLE
Incorrect license metadata

### ISSUE THREAD

**Issue by Smittyvb** [beeminder/road#154]
The `package.json` files say:
https://github.com/beeminder/road/blob/cb6f64cf9b2f656535d6f69b2167c541103c83b6/package.json#L36
https://github.com/beeminder/road/blob/cb6f64cf9b2f656535d6f69b2167c541103c83b6/jsbrain_server/package.json#L10

but there is no actual license file.

**Comment by dreeves** [comment]
Thanks for reporting this! Should be fixed now!

Note also that we'd like you to sign our CLA at http://beeminder.com/cla before contributing. Definitely let us know if any concerns!
