### ISSUE TITLE
Rounding error (?) with yaw=-1, dir=-1, aggday=sum

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#158]
See roundingerrormaybe.bb in privatesuite.

Beebrain says the delta is 0 and the safebuf is 0. A delta of 0 (i.e. vcur = roadval) should be safebuf +1, ie orange.

**Comment by bsoule** [comment]
another example of weirdness with this type of goal (we use it for fitbit netcalories): privatesuite/data/morephatrounding.bb

screenshot: the watermark & countdown both think there's +0 due tomorrow (which comports with orange), but the road value == vcur, and so it ought to be 3 or 4 days of buffer. also what's "+0 due" even mean?

![morephatrounding](https://user-images.githubusercontent.com/46881/93526128-d69f7980-f8eb-11ea-963e-b9c2233b3c01.png)

**Comment by dreeves** [comment]
I'm not sure now when we fixed this but I just confirmed that the example bb files generate the right output now!
