### ISSUE TITLE
Bad red-yesterday condition on odom goal

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#165]
See data/negative-value-odom.bb in privatesuite.

## Reseminata

1. Set asof = 2020-11-19
2. Set all the usual odom-goal settings (non-kyoom, odom, aggday=last)
3. Road matrix (including tini/vini and final road row):

```
2020-11-16, 0, null
2020-11-18, null, 7
2020-11-18, -1, null
2020-11-19", null, 0
2022-05-19, null, 7
```

4. Two datapoints:

```
2020-11-17, 1, "on the road"
2020-11-18, -1, "derail!"
```

## Expectata

Datapoint on 11-18 should not be red. Nor should the flatline datapoint on 11-19. They're both right on the bright line.

## Resultata

Datapoint is plotted red, graph is derailed, skull-and-crossbones watermark shows.

This caused a goal to get stuck in a recommit loop and be un-restart-able in Beebody.

![image](https://user-images.githubusercontent.com/9928/101839551-6e7dbf80-3af7-11eb-8a33-48842fc9819c.png)

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3604

**Comment by bsoule** [comment]
psst. you closed the wrong gissue, or referenced the wrong changelog here; that changelog line is "added a bunch of explanation to the weightloss help docs".
