### ISSUE TITLE
Latest SVG improvements broke SVGs in Safari and Firefox

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#177]
See missing-dots.bb in privatesuite. https://github.com/beeminder/privatesuite/blob/master/data/missing-dots.bb

But this applies to _every_ bb file.

Here's how it looks in Chrome vs Firefox:

![image](https://user-images.githubusercontent.com/9928/104374384-ad2bde80-54d6-11eb-8f9f-42c691fa3410.png)

![image](https://user-images.githubusercontent.com/9928/104374554-e2383100-54d6-11eb-96a4-13b0c124c8fb.png)

**Comment by adamwolf** [comment]
I played around in safari, and when I added "px" to #svg1 .dp's r attribute of 2.75, all the datapoints showed up.  Working on investigating more

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3637
