### ISSUE TITLE
Beebrain thinks these datapoints are red => derail

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#180]
Looks related / similar to https://github.com/beeminder/road/issues/165 -- which reported that bad red-yesterday condition on an odometer goal. I've got a do more goal with a negative kyoomed value (probably a weird corner case, because it's a dev goal and i made it negative because i was intentionally testing derailing a thing), and the road and kyoomed/agged data are at the same value for "yesterday", but beebrain is marking yesterday as red.

see privatesuite: https://github.com/beeminder/privatesuite/blob/master/data/negative-kyoom-value-derails.bb for bug file

beebrain plots datapoints as red:
<img width="593" alt="Screen Shot 2021-01-15 at 14 59 30" src="https://user-images.githubusercontent.com/46881/104786712-94276580-5742-11eb-8e3f-3fe4f3e53cf6.png">

road says: they should be safe:
[["2021-01-07",0,null],
["2021-01-14",null,0],
["2021-01-14",-1,null],
["2021-01-21",null,0],
["2021-01-22",null,0],
["2038-01-01",null,3]]

**Comment by dreeves** [comment]
I discussed with Bee and we think she accidentally used a Beebrain version from before the fix of #165 so we're comfortable closing this as cnr.

In any case the .bb file does not show this problem with current Beebrain.
