### ISSUE TITLE
top post datapoints

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#191]
i think the datapoints tab should be top posted. especially since then we can use pagination in the api and not load all the datapoints, cuz mostly you just care about the recent ones. also they're top posted on the graph page data tab. also if you top post them then you see your new datapoint appear immediately at the top of the list. otherwise you have to scroll through all the data to confirm / verify that it's there.

**Comment by saranli** [comment]
That's doable, but we have to load all the datapoints anyway since they are required by beebrain.
