### ISSUE TITLE
Can't undo in the sandbox

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#193]
I was playing in the sandbox (see Sandbox tab of [graph.beeminder.com](https://graph.beeminder.com)), and I'm not sure if this was a bug or if something else I clicked caused it to do this on purpose, but I pressed the "next day" button on a red goal, and so it advanced to the next day, showing a derailment/rerailment, but then there was no [Undo] for that first "next day" step. I could click "next day" more times and it advanced, and then I could undo those advances.. but the very first "next day" advance was un-undoable.

## Replicata

1. Load any red goal in the graph editor
2. Go to the Sandbox tab
3. Click the "Next Day" button
4. Goal derails/rerails

## Expectata

I want to click "Undo" to undo that.

## Resultata

The "Undo" button is grayed out. (If I click "Next Day" without derailing, I can undo it fine.)

## Related

* #235 
* #215 
* #187 

*Keywords: graph editor, sandbox, undo button,*

**Comment by dreeves** [comment]
http://beeminder.com/changelog#4133
