### ISSUE TITLE
Blanky graph with only skull and watermark

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#222]
Here was an odd graph I ran into while poking at the edges of an error condition, trying to figure out what caused it.

<img width="748" alt="Screen Shot 2021-07-20 at 19 44 41" src="https://user-images.githubusercontent.com/46881/126423240-0f2902be-653f-4f4c-b71c-b3e833326272.png">

Conditions / actions leading up to this weird state: I was testing stuff related to the "deleting the restart/recommit datapoint instaderails", so I had a goal where the road was very far above my current value, and then a row moving the road to my current value on yesterday. So the road was something like:

[[tini-a-very-long-time-ago, vini, nil],
[yesterday, nil, 15],
[yesterday, 81, nil],
[end-date, nil, 15]]

the last several datapoints were:

(3-months ago, 1, "last data entered was a long time back")
(yesterday, 0, "restart")

When I deleted the restart datapoint, is when this happened. So adding a (2021-07-19, 0) datapoint should cause a normal graph. 

BB file: https://github.com/beeminder/privatesuite/commit/1c43732dfa3f6538c7e5ba120ea579e05b395813 aka emptyblankskullgraph.bb

**Comment by dreeves** [comment]
Fixed in dev as part of the fix for #223!

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3876
