### ISSUE TITLE
Include external resources in SVG

### ISSUE THREAD

**Issue by adamwolf** [beeminder/road#277]
I've noticed that graphs (sometimes? always?) contain a reference to [bullseye.png](https://s3.amazonaws.com/bmndr/road/bullseye.png).  At least sometimes, it's not visible.  I'm not sure if it's part of the spec and required, but I'm seeing Chrome, Firefox, and Safari all fetching that png, even if its position is quite a bit outside of the viewbox and it's completely invisible.

(There are other external resources, too.)

# Is this a good idea?
I don't know everything about this, and I haven't thought it completely through, but I'm not sure this is a good idea.

* For instance, if I were to save my SVG to my computer, and open it up when I am offline, I would expect the SVG to load properly.  Instead, I get something like this:
<img width="721" alt="Screen Shot 2022-09-07 at 10 13 03 AM" src="https://user-images.githubusercontent.com/35681/188915260-102e89ca-2907-4eb4-80d4-3ab437980107.png">
with a shaded square where the background lemniscate normally is, and an old-school Broken Image icon where the bullseye normally goes.

* I would also be surprised if we changed what the bullseye looks like, but memorialized users graphs look different or broken. (Maybe I shouldn't, though? Haven't thought it through.)

* There are lots of SVGs that are very tiny, hundreds of bytes, and they include a reference to a 10kb png that isn't shown, but the browser downloads it anyway.

* If you look at the SVG in megaresolution, the bullseye image is going to stay the same resolution/size, while everything else embedded in the SVG around it is razor-sharp.

* If someone goes their goal page or opens their graph SVG while S3 is having trouble, their graph SVG may seem to load fine but parts of it would be missing or broken.

# What do we do?

* Of course, we could do nothing. :)

* We could add caching and browser caching hints.  Right now, the external resource links are aiming at the S3 bucket.  We could point to the Cloudfront CDN in front of the S3 bucket, which would speed it up for folks who aren't close to the S3 bucket region.  We could add browser caching hints, so the browser would keep bullseye.png et al in the cache for a year.  However, both of these would mean that changing the bullseye would be tricky.  If we ever needed a different bullseye, we'd have to use a different name, or else we couldn't predict how a graph shows up on a client--we can't see inside the browser cache.  (There's a similar snag with Cloudfront, but we could issue an invalidation for $$$.)  To work around this, we would want to do something like version the external resources.  Instead of bullseye.png, we would point to bullseye-<digest>.png, or bullseye-1.png, or whatever.

* We could add the bullseye conditionally to the graph, so that when it isn't in the view, it doesn't get included.

* We could make an svg version of the bullseye, and add the bullseye group into the svg directly.  This would "bake in" the bullseye, avoid the DNS lookup, avoid caching issues, avoid resolution issues, avoid offline issues...  We could still only add it conditionally.  I would want to make sure the generation time changes and the output sizes are benchmarked, but I can't imagine not being able to make an awesome bullseye in <10kb of SVG!  (We may be able to do well in 500 bytes of SVG!)

I'm sure there are parts of this I haven't thought about!

I haven't gone through all the external resources, but I think we should think through each of them.

**Comment by dreeves** [comment]
Making SVG versions of those sprites makes a ton of sense to me! I just tried using a few free online conversion tools and they were all garbage. Happy to pay a nice bounty in premium credit for anyone who wants to take a crack at it.

Or possibly Uluc still has the source file in whatever he used to create that bull's eye in the first place and could actually generate it as SVG directly? Not sure about other sprites like the skull and crossbones though.

**Comment by rperce** [comment]
```
<svg style="position: absolute; top: 0px; left: 0px; display: block;" width="80" height="120" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" id="svg">    
  <!-- depth -->
  <rect x="41" y="6" width="15" height="106" fill="#ffbbbb"></rect>
  <ellipse cx="56" cy="60" rx="21" ry="53" fill="#ffbbbb"></ellipse>
  
  <!-- outer ring -->
  <ellipse cx="41" cy="60" rx="23" ry="53" fill="red"></ellipse>
  <ellipse cx="40" cy="60" rx="17" ry="41" fill="white"></ellipse>
  
  <!-- inner ring -->
  <ellipse cx="39" cy="60" rx="14" ry="31" fill="red"></ellipse>
  <ellipse cx="38" cy="60" rx="9" ry="20" fill="white"></ellipse>
  
  <!-- bullseye -->
  <ellipse cx="37.5" cy="60" rx="5" ry="10" fill="red"></ellipse>
</svg>
```

**Comment by rperce** [comment]
Per Discord: I didn't do any math to make sure the centers and radii are exactly mathematically perfect for being an actual bunch of circles viewed at an angle, but it's simple enough to tweak the `cx` and `rx` values if desired!

**Comment by adamwolf** [comment]
The default settings on [svgomg](https://jakearchibald.github.io/svgomg/) (a web svgo) save a little bit more, by omitting version, and replacing the rect with a path, giving:

```
<svg width="80" height="120" xmlns="http://www.w3.org/2000/svg"><path fill="#fbb" d="M41 7h15v106H41z"/><ellipse cx="56" cy="60" rx="21" ry="53" fill="#fbb"/><ellipse cx="41" cy="60" rx="23" ry="53" fill="red"/><ellipse cx="40" cy="60" rx="17" ry="41" fill="#fff"/><ellipse cx="39" cy="60" rx="14" ry="31" fill="red"/><ellipse cx="38" cy="60" rx="9" ry="20" fill="#fff"/><ellipse cx="37.5" cy="60" rx="5" ry="10" fill="red"/></svg>
```
which is 431 bytes, a savings of 30 whole bytes!!!! :)

**Comment by adamwolf** [comment]
If folks are looking for references for the other ones ;), they're at https://github.com/beeminder/road/blob/f96ec7a1e53530c582c7fbc09f511d82f7b8a0a3/src/bgraph.js#L287

**Comment by rperce** [comment]
Hey, 30 bytes is nothing to sneeze at when that's a whole 6.5% :D

**Comment by rperce** [comment]
i bet you could replace the first ellipsis with an ellipse-segment in the `path` too!

**Comment by rperce** [comment]
heck yes you can
```
<svg width="80" height="120" xmlns="http://www.w3.org/2000/svg"><path d="M41 7h15a21 53 0 0 1 0 106H41z" fill="#fbb"/><ellipse cx="41" cy="60" rx="23" ry="53" fill="red"/><ellipse cx="40" cy="60" rx="17" ry="41" fill="#fff"/><ellipse cx="39" cy="60" rx="14" ry="31" fill="red"/><ellipse cx="38" cy="60" rx="9" ry="20" fill="#fff"/><ellipse cx="37.5" cy="60" rx="5" ry="10" fill="red"/></svg>
```
391 bytes!

**Comment by adamwolf** [comment]
When we add this to the existing svg, I don't think we'll use that namespace, right, since that's going to already be there...

**Comment by saranli** [comment]
I've just pushed a branch (pngpurge) which (hopefully) addresses this issue. This is a summary of the implementation and findings.

The way svg's can be embedded is through the use of the "defs" field in the svg. However, the main issue I enountered with replacing the four pngs (bullseye, infinity, smiley, jollyroger) was that svg snippets defined within the "defs" and later used with svg:use do not allow specifying explicit width/height. As a solution, I had to resort to "transform" and "transform-origin" to properly scale the predefined svg snippets.

The four png's mentioned above were also inherited from earlier versions of beebrain, python and possibly earlier, so I did not have svg's for them. I imported them in inkscape and traced outlines with paths, followed with an export as "optimized svg". I This yields acceptable results. Note, also, that svg headers and such are not needed in the defs section, just various graphical components.

Finally, jsbrain now creates svg snippets within defs only when needed, except the bullseye which is always embedded. I kept that in place mainly to handle dynamic scrolling, but that could also be optimized for static svgs if needed.

**Comment by adamwolf** [comment]
Sounds great!

**Comment by dreeves** [comment]
Here's a very zoomed-in before and after shot:

![image](https://user-images.githubusercontent.com/9928/194176226-2158d800-e50c-4930-936c-5f2db7e6517a.png)

![image](https://user-images.githubusercontent.com/9928/194176384-1b807df5-8a70-409d-a367-d474dc72cca6.png)
