### ISSUE TITLE
Ratchet produces invalid road

### ISSUE THREAD

**Issue by cpcallen** [beeminder/road#32]
To reproduce:

- Find a do-more goal with > 1 day safety buffer.
- In box marked "Reduce safety buffer to:", type `1`.
- Click "Ratchet"
- Click "Submit"

Expected result: road is updated.

Actual result: an error:

> ERROR! "that doesn't look like a road matrix". Email support@beeminder.com for more help!

Workaround: in the road matrix(?), find the newly-inserted "infinity" entry, and click the number to the left of "infinity".  Before:

<img width="469" alt="screen shot 2018-06-13 at 14 59 39" src="https://user-images.githubusercontent.com/5603958/41380667-924dde0a-6f1a-11e8-93c1-653a3d144956.png">

After:

<img width="479" alt="screen shot 2018-06-13 at 14 59 55" src="https://user-images.githubusercontent.com/5603958/41380681-9b2cf2a4-6f1a-11e8-87e8-97aca17111f8.png">

After which clicking "Submit" will succeed in saving the new road.

**Comment by saranli** [comment]
This is now fixed in the current repository. We have not yet deployed it on the glitch version, but should come soon.
