### ISSUE TITLE
Hotlink image assets hosted on beeminder.com

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#35]
Uluc: 
> Looks like there is a small issue with the paths to png files, including skull and such
> Oh yes, we need to upload those files into glitch assets and change the links in roadeditor.js
> The PNG variable has them in roadeditor.js
> Perhaps these assets should refer to a beeminder link, that might be best

**Comment by dreeves** [comment]
assets in question:

```
smiley.png
bullseye.png
bullseye_old.png
jollyroger_sqr.png
infinity.png
```

does this work:

1. create static links by sticking the images somewhere like beeminder.com/images/*.png since that's presumably expedient and we can hotlink to those absolute URLs
2. put them in AWS if that makes sense later and have redirects so the links above don't break

**Comment by bsoule** [comment]
https://s3.amazonaws.com/bmndr/road/smiley.png
https://s3.amazonaws.com/bmndr/road/bullseye.png
https://s3.amazonaws.com/bmndr/road/bullseye_prev.png
https://s3.amazonaws.com/bmndr/road/jollyroger.png
https://s3.amazonaws.com/bmndr/road/infinity.png
