### ISSUE TITLE
"Start Date" & "End Date" misaligned

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#37]
Looks like everything is shifted to the right by one column:

![image](https://user-images.githubusercontent.com/9928/49412864-d1773780-f722-11e8-9a3c-72c31b9faf5b.png)

**Comment by saranli** [comment]
Done. This was only visible on google chrome, not chromium or firefox strangely. It was fixed by using d3.ascending in the sorting call within updateTableButtons with commit a65f7b17752ed030fa9523595fc389c79337e7b7
