### ISSUE TITLE
Actually use the vmin/vmax settings

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#45]
one user pointed this out: "I tried the js graphs, I don't seem to be able to set the Y axis limit (will not update)."

of course this won't matter much when graphs are always interactive on the website but might as well match pybrain on this for now and then we'll decide what to do when/if it no longer makes sense to expose vmin/vmax/tmin/tmax to the user

**Comment by saranli** [comment]
If you can paste the BB file contents here, I can test for this particular goal.

**Comment by saranli** [comment]
I also think this is fixed by 7790f436351f869350e60237a102fb43aafd2cb3. Needs testing on goals where this is reported to be an issue though.
