### ISSUE TITLE
Integery?

### ISSUE THREAD

**Issue by adamwolf** [beeminder/road#54]
On my gmailzero goal https://www.beeminder.com/adamwolf/gmailzero, I have integery set, but the goal tells me "+0.0 ending in 6 months or pay $0".  I expect "+0 ending in 6 months or pay $0".

If I switch back to pybrain and add a new datapoint, it shows me what I expect.  If I go back to jsbrain, and add a new datapoint, it shows me +0.0 again.

I do not know how to get the .bb file.

**Comment by dreeves** [comment]
Adam's bb file is now here: https://github.com/beeminder/privatesuite/blob/master/integery.bb

**Comment by dreeves** [comment]
@adamwolf how about now?
