### ISSUE TITLE
Yellow and Blue make Green

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#56]
Maybe not worth addressing but I find Pybrain's version of this graph pretty with the green overlap for the intersection of the turquoise swath (aka aura) and the yellow brick road:

pybrain:

![image](https://user-images.githubusercontent.com/9928/51772661-6ce0b500-20a1-11e9-971f-ae440e797d8a.png)

jsbrain:

![image](https://user-images.githubusercontent.com/9928/51772702-85e96600-20a1-11e9-8575-dcc6d67ab9eb.png)

bb file: https://github.com/beeminder/privatesuite/blob/master/overlap.bb

It's ok to close this as `aok` if you think jsbrain's is better or `nix` if you think it's definitely not worth computing intersections or `zzz` to just say we'll think about it later.

**Comment by saranli** [comment]
Is this still on your wishlist? I personally don't think it will be worth the effort and complexity since it might require an additional svg object for the green region. Please review and close if not critical.

**Comment by bsoule** [comment]
I think the jsbrain one looks better because it is more subtle and less
distracting
