### ISSUE TITLE
Memory leak in Road Editor with Safari?

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#60]
https://forum.beeminder.com/t/visual-road-editor-requires-50-gib-of-ram/4891

**Comment by saranli** [comment]
Can we get the bb file for this? I doubt it's just a safari issue.

**Comment by dreeves** [comment]
Here it is: https://github.com/beeminder/privatesuite/blob/master/memleak.bb

**Comment by saranli** [comment]
I don't have access to safari anywhere. Could one of you look into this and perhaps attempt to get a memory allocation report or something to see where the allocated memory could be going to?

**Comment by bsoule** [comment]
I notice this is the same goal from #74 -- could this be the same cause?
