### ISSUE TITLE
svg is not scaling w/browser size the way a .png does

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#61]
I think this may want some changes to the generated svg file. 

First off, this is happening when the svg is included from s3 (but not when it's a local file, for added flavor...):

![ttest___b_ttest_goal_page](https://user-images.githubusercontent.com/46881/52308835-3e8d9000-2953-11e9-9ac9-a17cd2ec2aca.png)

I can fix it by adding a height & width to the object tag, but then the object doesn't scale as the page gets smaller, like the image version does. 

The css for the image tag has:
``` 
max-width: 696 
width: 100%
height: auto
```

But putting similar settings on the object that houses the svg causes the object to resize, not the SVG that it houses... (also having annoyances with the height part... but anyway).

So.. is it possible to get the svg to resize with the page/the object? Like something that'll preserve aspect ratio and make the width always be as big as the container it's in? In fact at the moment the png is scaled smaller as the page gets smaller, but it has that max width of 696, which is not something we need to enforce with the .svg version, since it's all vectory!

**Comment by saranli** [comment]
Ok, will look into it but the svg is constructed to have a fixed height and width with many components in it positioned accordingly. I am not sure scaling the width and height of the svg would be an option after generation. We may need to figure out a way to scale it like in zooming. I will try some stuff out.

**Comment by saranli** [comment]
May have fixed it in develop by adding tags as in https://stackoverflow.com/questions/644896/how-do-i-scale-a-stubborn-svg-embedded-with-the-object-tag

**Comment by bsoule** [comment]
Almost there -- need to also adjust the width and height declaration w/in the svg to be 100%:

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMinYMin meet" viewBox="0 0 696 453" width="100%" height="100%" class="bmndrsvg">`

I'm not sure about the "viewBox" declaration, which also encodes the 696/453 width. My experimentation seems to work without changing those. 

However, we should get someone else trying this out with the .svgs other than just me... I'm experiencing the page being super laggy when it loads and resizes the svg and stuff, but I think that's just me and my stupid laggy computer. Still, the pngs do seem to be a bit better on the lagginess, so definitely worth playing with a bit to make sure we're not going to double our page load times or something by including svg instead of png?

**Comment by saranli** [comment]
SVG filesize can be quite a bit larger than pngs for goals with lots of road segments and datapoints. That could definitely introduce some lagginess in loading the resource, and possibly in rendering.

**Comment by dreeves** [comment]
Any chance it makes sense to pick a threshold (on datapoints and/or road segments) for using the SVG vs the PNG? Ignore me if that's messy/annoying/dumb.

**Comment by saranli** [comment]
I think it would make more sense to have a threshold directly on filesize if that's possible, but it might be sort of annoying for the user since advanced users who would want scalable graphs are most likely those with lots of datapoints?

**Comment by dreeves** [comment]
True. I don't like the idea of making it a setting or anything though. So maybe we just do svg for everyone and see how bad the file size problem turns out to be?

**Comment by saranli** [comment]
Can we close this now?
