### ISSUE TITLE
loadGoal: "Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#62]
We're getting this error intermittently from jsbrain (~1 every 3 days). Here's an example from Dubnium:

Full error message from jsbrain-error.log: 
```
(node:5762) Warning: No such label '(1:353689)  Page render (b28bbb57-fccb-4d4e-968f-9c54857ed9fc)' for console.timeEnd()
```

And here's the jsbrain-out.log output for it:

```
(1:353689) ============================================
(1:353689) Request url=/?inpath=%2Fvar%2Fwww%2Fbeebrain%2Fnonce&outpath=%2Fvar%2Fwww%2Fjsbrain%2Fnonce&pyjson=%2Fvar%2Fwww%2Fbeebrain%2Fnonce%2Fb28bbb57-fccb-4d4e-968f-9c54857ed9fc.json&slug=b28bbb57-fccb-4d4e-968f-9c54857ed9fc
(1:353689) <BEEBRAIN> b28bbb57-fccb-4d4e-968f-9c54857ed9fc @ 2019-02-04 06:31:39
(1:353689)  Page creation (b28bbb57-fccb-4d4e-968f-9c54857ed9fc): 230.608ms
(1:353689)  PAGE LOG: ERROR (loadGoal): Cannot read property '0' of undefined
(1:353689)  Page render (b28bbb57-fccb-4d4e-968f-9c54857ed9fc): 177.527ms
(1:353689)  renderer.js ERROR: Could not extract JSON from page!
(1:353689)  Total processing (b28bbb57-fccb-4d4e-968f-9c54857ed9fc): 426.700ms
(1:353689) </BEEBRAIN> (pending: 0)
```

**Comment by bsoule** [comment]
(doesn't look like we clobbered the .bb file before jsbrain could run or anything like that. the next run of the graph on the same server was 190 seconds later -- well after the 1.5 seconds between pybrain and jsbrain's run)

**Comment by saranli** [comment]
Does this still happen? If so, would it be possible to get the associated bb file?

**Comment by saranli** [comment]
Have you seen this again recently? Can we close the issue?

**Comment by bsoule** [comment]
It's pretty rare. I had to go back to the 15th to find an instance. There have been successful trips through jsbrain since then, and since it's been ~week, I don't have the actual bb file that failed, but I have uploaded a current copy of the bb file to the private suite repo in triage.

**Comment by saranli** [comment]
Added a stack trace print to the place that detects page errors during rendering. When deployed, this should give us a bit more info when this error happens again.

**Comment by saranli** [comment]
Based on the more detailed error logs I enabled, I now believe this issue may be originating from goals where all datapoints are in the future. I will put in a check to display an error if that's the case, but is there any way to confirm if goal which generate this error are indeed without any datapoints before or on asof?

**Comment by saranli** [comment]
I believe this is resolved after various fixes following the enabling of better error logs. Have not seen it since April
