### ISSUE TITLE
Sanity checker

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#67]
the big picture is we should be able to edit the source code and completely in the background it makes a happy sound if everything in the test suite of bb files stayed the same and makes a sad sound if anything changed, with a way to see the diff of what changed. and if what changed was ok there should be an easy way to reset the sanity checker so that becomes the new baseline. (in pybrain i did that by deleting sanity.txt which it would notice and automatically recreate it with the current version of pybrain)

**Comment by dreeves** [comment]
also the old sanity.py would show a progress bar for getting through the whole test suite but immediately alert you when it found a difference. you could see that right away by comparing insanechunk.txt to sanechunk.txt and then wait for the full insanity.txt to diff with sanity.txt

**Comment by saranli** [comment]
I think this is mostly done now.
