### ISSUE TITLE
Upgrade D3 to version 5

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#68]

**Comment by saranli** [comment]
This was already mostly done, I edited some leftover files and updated road-staging with it. If you can test it on road-staging (including tutorial and sandbox links), we can close this issue, I think.

**Comment by dreeves** [comment]
In case it's related to D3 version, tutorial seems to be messed up right now:

![image](https://user-images.githubusercontent.com/9928/57825449-d4576900-7753-11e9-856a-ebe42edd9727.png)

See black rectangle instead of text box. Also the graph got tiny when viewed in Chrome/macOS.

**Comment by saranli** [comment]
That black bar was not due to d5, it was just me forgetting that there was another css class to modify for messages. I have not seen any d5 related glitches so far, so closing this.
