### ISSUE TITLE
Road editor take-a-break submitted road from a different goal?

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#75]
## Reseminata

TODO

## Expectata

TODO

## Resultata

TODO

## Nota Nebulosa

User used take-a-break on road.beeminder.com and it submitted what appears to be a totally different road from the original (different tini and stuff).

Check logs for https://www.beeminder.com/cgamer1/onlyeatjunkfoodwithotherpeople

**Comment by dreeves** [comment]
We probably need to close this for lack of any leads on reproducing it, but if anyone has seen this happen recently, definitely holler!
