### ISSUE TITLE
New graphs don't show up in road editor

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#76]
## Reseminata

1. Create a fresh account (or use one of the test accounts -- testinfinibee, testbeeplus, testbeemium)
2. Create 2 goals
3. Go to road.beeminder.com

## Expectata

That I'd see the 2 goals in the dropdown.

## Resultata

The dropdown is empty, as if the account has no goals.

## Nota Nebulosa

Seems potentially related to #75 but easier.

**Comment by bsoule** [comment]
i created a new goal this morning that's definitely showing in road.beeminder when I go there now. is road.beeminder fresh / reloaded? you're definitely signed into the correct account etc?

**Comment by dreeves** [comment]
that's for your own account though, right? i also don't see the problem for myself as user d. what if you do it from scratch with a new account after logging out?

**Comment by saranli** [comment]
Can't reproduce this either. Tried it with testinfinibee. Also created a new testsaranli user, tried with two goals, no problems. Firefox on linux
