### ISSUE TITLE
Beebrain errors render as black boxes in the SVG

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#78]
![image](https://user-images.githubusercontent.com/9928/58372527-76551f00-7ed3-11e9-97d6-837b2e156fb6.png)

The PNG looks fine:

![image](https://user-images.githubusercontent.com/9928/58372531-85d46800-7ed3-11e9-9351-cf370a547461.png)

**Comment by dreeves** [comment]
Not _too_ urgent since these are rare and we fix them when they happen and the error text is still kinda shown above the graph. Incidentally, when this particular graph is working it looks pretty dang cool:

![image](https://user-images.githubusercontent.com/9928/58372556-eb285900-7ed3-11e9-924a-e3ebcd933550.png)

**Comment by saranli** [comment]
Latest commit should fix this. It had to do with not embedding the proper styling into the SVG after changes to the overlay css components.

**Comment by dreeves** [comment]
https://github.com/beeminder/road/commit/d713cb4b5ea64d252014e2bc58a8f301749f83a0
