### ISSUE TITLE
Issue installing with Node 12?

### ISSUE THREAD

**Issue by adamwolf** [beeminder/road#81]
I was unable to install jsbrain_server when I used Node 12.

```
../sleep.cc:6:11: error: no member named 'Handle' in namespace 'v8'
using v8::Handle;
```

When I switched to Node 11 from Node 12, I was able to install jsbrain_server just fine.

**Comment by dreeves** [comment]
Node 10 is the current LTS so maybe we shouldn't worry about anything >10?

**Comment by adamwolf** [comment]
It's working fine on 14.  I'm moving the docker container to 14.
