### ISSUE TITLE
hashtags on graph not supporting UTF8 / non-ascii characters?

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#89]
Reported by a user:
1) enable showing hashtags
2) add datapoint with "#zdjecia" comment - annotation will be shown
3) add datapoint with "#zdjęcia" comment - annotation will not be shown

I'm thinking this is at Beebrain level. The hashtag's not shown at all if there's a special character. I checked the .bb file and the comments appear normally in the data section of the file.

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3171
