### ISSUE TITLE
skull & crossbones erroneously?

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#98]
Added a new bb to the private suite -- https://github.com/beeminder/privatesuite/blob/master/data/luz-but-ended.bb -- for a goal that ended, and it looks like it ended in the green (i.e. data above the road), but beebrain is using the skull & crossbones image and it registered as a "lose" on beeminder's side, so I think the luzdate or safety buffer disagreed with that green-ness?

**Comment by dreeves** [comment]
Another example, from Nikki:
https://github.com/beeminder/privatesuite/blob/master/data/spurious-skull.bb

**Comment by dreeves** [comment]
I suspect this fix will also fix https://forum.beeminder.com/t/whittle-down-goal-rate-is-too-slow-for-end-date/6689/20?u=dreev
